### PR TITLE
fromJSONField: Include JSONPath on JSON parse errors

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by phadej** [comment]
this new `fromJSON` doesn't seem to be used anywhere?

**Comment by sol** [comment]
> this new `fromJSON` doesn't seem to be used anywhere?
My bad, fixed.

**Comment by sol** [comment]
@phadej `aeson`'s `fromJSON` does not include the `JSONPath` to the location where parsing failed in error messages.  I addressed this by using `ifromJSON`.

**Comment by phadej** [comment]
@sol this looks good.

**Comment by phadej** [comment]
Merged, thanks for the ping

**Pull request merged**
