### PR TITLE
Escape double '??' to a literal '?'

### PR DESCRIPTION
**Pull request by Vlix**
This was already a pull request in lpsmith's repo, but now moved here.

This change seeks to allow for the usage of the JSON operators new to PostgreSQL since version 9.4 that use a question mark (namely: `?`, `?|` and `?&`) by way of escaping double question marks to a literal question mark in the resulting query.

This shouldn't break any existing code, since any occurrence of double question marks of which none are to be replaced by a value would be an error in any pre-existing code.

### CODE REVIEW

**Comment by Vlix** [comment]
I'm suspecting this travis build also uses PostgreSQL 9.3 or less.
I'm not sure how to change which version of PostgreSQL is used by the Travis build. Help would be appreciated.

**Comment by phadej** [comment]
https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version

**Comment by phadej** [comment]
Yet, ?? Escaping can be test insite string literal, can't it?

**Comment by Vlix** [comment]
> Yet, ?? Escaping can be test insite string literal, can't it?
> […](#)
> Sent from my iPhone
> On 1 Feb 2019, at 23.05, Oleg Grenrus ***@***.***> wrote: https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version Sent from my iPhone > On 1 Feb 2019, at 14.49, Felix Paulusma ***@***.***> wrote: > > I'm suspecting this travis build also uses PostgreSQL 9.3 or less. > I'm not sure how to change which version of PostgreSQL is used by the Travis build. Help would be appreciated. > > — > You are receiving this because you are subscribed to this thread. > Reply to this email directly, view it on GitHub, or mute the thread.

I've added a test that just uses the function that escapes double question marks and breaks on single ones.

The other tests I already put in there make sure the question mark operators behave as expected and that double ?? do indeed turn into something PostgreSQL can use for JSON operations.

**Comment by Vlix** [comment]
Any idea if/when this will be merged?

**Comment by phadej** [comment]
I'm steadily working through issues

**Comment by phadej** [comment]
squashed in #8

**Pull request closed without merging**
